payment_service:
  url: "https://payment.masumi.network/api/v1"
  access_token: "your_payment_access_token"

registry_service:
  url: "https://registry.masumi.network/api/v1"
  access_token: "your_registry_access_token"